export const TARGET_PRIMARIE = 35;
export const TARGET_SECONDARIE = 15;
export const TARGET_INVESTIMENTI = 25;

export const TARGET_RISPARMIO =
  100 - TARGET_PRIMARIE - TARGET_SECONDARIE - TARGET_INVESTIMENTI;

export const TARGET_NETTO =
  TARGET_INVESTIMENTI + TARGET_RISPARMIO;
